<?php
/**
 * RenderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\RendererService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Renderer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\RendererService;

use VentureLeap\RendererService\Configuration;
use VentureLeap\RendererService\ApiException;
use VentureLeap\RendererService\ObjectSerializer;

/**
 * RenderApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\RendererService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RenderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteRenderItem
     *
     * Removes the Render resource..
     *
     */
    public function testDeleteRenderItem()
    {
    }

    /**
     * Test case for getRenderCollection
     *
     * Retrieves the collection of Render resources..
     *
     */
    public function testGetRenderCollection()
    {
    }

    /**
     * Test case for getRenderItem
     *
     * Retrieves a Render resource..
     *
     */
    public function testGetRenderItem()
    {
    }

    /**
     * Test case for postRenderCollection
     *
     * Creates a Render resource..
     *
     */
    public function testPostRenderCollection()
    {
    }

    /**
     * Test case for putRenderItem
     *
     * Replaces the Render resource..
     *
     */
    public function testPutRenderItem()
    {
    }
}
