<?php
/**
 * TemplateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\RendererService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Renderer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\RendererService;

use VentureLeap\RendererService\Configuration;
use VentureLeap\RendererService\ApiException;
use VentureLeap\RendererService\ObjectSerializer;

/**
 * TemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\RendererService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TemplateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteTemplateItem
     *
     * Removes the Template resource..
     *
     */
    public function testDeleteTemplateItem()
    {
    }

    /**
     * Test case for getTemplateCollection
     *
     * Retrieves the collection of Template resources..
     *
     */
    public function testGetTemplateCollection()
    {
    }

    /**
     * Test case for getTemplateItem
     *
     * Retrieves a Template resource..
     *
     */
    public function testGetTemplateItem()
    {
    }

    /**
     * Test case for postTemplateCollection
     *
     * Creates a Template resource..
     *
     */
    public function testPostTemplateCollection()
    {
    }
}
